server:
  port: 8081
  servlet:
    context-path: /auth
# mybaits-plus\u914D\u7F6E
mybatis-plus:
  # MyBatis Mapper\u6240\u5BF9\u5E94\u7684XML\u6587\u4EF6\u4F4D\u7F6E
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # \u81EA\u52A8\u5237\u65B0Mapper\u5BF9\u5E94\u7684XML\u6587\u4EF6
    refresh: true
    # \u5173\u95EDMP3.0\u81EA\u5E26\u7684banner
    banner: false
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u672A\u8BBE\u7F6E\u4E3B\u952E\u7C7B\u578B",2:"\u7528\u6237\u8F93\u5165ID",3:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 4:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: 0
      #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
      field-strategy: 1
      # \u903B\u8F91\u5220\u9664\u914D\u7F6E
      # \u903B\u8F91\u5220\u9664\u5168\u5C40\u503C\uFF081\u8868\u793A\u5DF2\u5220\u9664\uFF0C\u8FD9\u4E5F\u662FMybatis Plus\u7684\u9ED8\u8BA4\u914D\u7F6E\uFF09
      logic-delete-value: 1
      # \u903B\u8F91\u672A\u5220\u9664\u5168\u5C40\u503C\uFF080\u8868\u793A\u672A\u5220\u9664\uFF0C\u8FD9\u4E5F\u662FMybatis Plus\u7684\u9ED8\u8BA4\u914D\u7F6E\uFF09
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
# \u6570\u636E\u6E90
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.104.223.25:3306/xiaoniu?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/

