server:
    port: 9001
    servlet:
      context-path: /ui
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:9000/auth/oauth/token
#      accessTokenUri: http://www.xiaoniuzp.com/auth/oauth/token
#      userAuthorizationUri: http://www.xiaoniuzp.com/auth/oauth/authorize
      userAuthorizationUri: http://localhost:9000/auth/oauth/authorize
    resource:
      #token-info-uri: http://localhost:8081/auth/oauth/check_token
      userInfoUri: http://localhost:9000/auth/user/me
#      userInfoUri: http://www.xiaoniuzp.com/auth/user/me
#spring:
#  thymeleaf:
#    cache: false
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#    url: jdbc:mysql://localhost:53306/xnzp_base?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    url: jdbc:mysql://10.122.24.45:3306/xnzp_base?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000